### PR TITLE
handle case where multiple UPNP services answers

### LINKED ISSUE #17: handle multiple UPNP service
I just setup a new network stack at my office based on ubiquity hardware: 
* router USG-3P
* controller cloud key gen 2
...

It appears that both the router and the controller are UPNP device but erlang-nat stop at the first one during the discovery and fail with a 404 error. Here a little snippet of the failure (upnp v2 discovery patched with some printing):

```erlang
31> natupnp_v2:discover().
got packet=<<"HTTP/1.1 200 OK\r\nCache-Control: max-age = 60\r\nExt:\r\nLocation: http://192.168.1.7:8080/upnp\r\nSERVER: UPnP/1.0 UniFi/5.10.25\r\nST: upnp:rootdevice\r\nUSN: uuid:3C86D905-39E4-4FDC-963C-04E19F2791BB::upnp:rootdevice\r\n\r\n">> ip={192,
                                                                                                                                                                                                                                                          168,
                                                                                                                                                                                                                                                          1,
                                                                                                                                                                                                                                                          7}
{error,"404"}```

However when you listen actively (and not only once) on the UDP socket you can see that multiple devices will send a message in response:

```erlang
32>  ST = <<"urn:schemas-upnp-org:device:InternetGatewayDevice:2" >>,
32> 
32> MSearch = [<<"M-SEARCH * HTTP/1.1\r\n"
32>                  "HOST: 239.255.255.250:1900\r\n"
32>                  "MAN: \"ssdp:discover\"\r\n"
32>                  "ST: ">>,  ST, <<"\r\n"
32>                                   "MX: 3"
32>                                   "\r\n\r\n">>].
[<<"M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: \"ssdp:discover\"\r\nST: ">>,
 <<"urn:schemas-upnp-org:device:InternetGatewayDevice:2">>,
 <<"\r\nMX: 3\r\n\r\n">>]
33> {ok, Sock} = gen_udp:open(0, [{active, true}, inet, binary]).
{ok,#Port<0.174>}
34> gen_udp:send(Sock, "239.255.255.250", 1900, MSearch).        
ok
35> flush().
Shell got {udp,#Port<0.174>,
               {192,168,1,7},
               1900,
               <<"HTTP/1.1 200 OK\r\nCache-Control: max-age = 60\r\nExt:\r\nLocation: http://192.168.1.7:8080/upnp\r\nSERVER: UPnP/1.0 UniFi/5.10.25\r\nST: upnp:rootdevice\r\nUSN: uuid:3C86D905-39E4-4FDC-963C-04E19F2791BB::upnp:rootdevice\r\n\r\n">>}
Shell got {udp,#Port<0.174>,
               {192,168,1,7},
               1900,
               <<"HTTP/1.1 200 OK\r\nCache-Control: max-age = 60\r\nExt:\r\nLocation: http://192.168.1.7:8080/upnp\r\nSERVER: UPnP/1.0 UniFi/5.10.25\r\nST: upnp:rootdevice\r\nUSN: uuid:3C86D905-39E4-4FDC-963C-04E19F2791BB::upnp:rootdevice\r\n\r\n">>}
Shell got {udp,#Port<0.174>,
               {192,168,1,1},
               1900,
               <<"HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=120\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nUSN: uuid:ce49f358-bba6-4485-ab1a-f42d90514224::urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nEXT:\r\nSERVER: Debian/wheezy UPnP/1.1 MiniUPnPd/2.1\r\nLOCATION: http://192.168.1.1:47548/rootDesc.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: 1561361365\r\nBOOTID.UPNP.ORG: 1561361365\r\nCONFIGID.UPNP.ORG: 1337\r\n\r\n">>}
Shell got {udp,#Port<0.174>,
               {192,168,1,1},
               1900,
               <<"HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=120\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nUSN: uuid:ce49f358-bba6-4485-ab1a-f42d90514224::urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nEXT:\r\nSERVER: Debian/wheezy UPnP/1.1 MiniUPnPd/2.1\r\nLOCATION: http://192.168.1.1:47548/rootDesc.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: 1561361365\r\nBOOTID.UPNP.ORG: 1561361365\r\nCONFIGID.UPNP.ORG: 1337\r\n\r\n">>}
ok
```

Only the router is answering with an ST header  `urn:schemas-upnp-org:device:InternetGatewayDevice:2`.

To fix it we should probably listen on the socket until we get a valid header andonly stop at this time.

### PR DESCRIPTION
**Pull request by benoitc**
in some infrastructure with badly configured UPNP,
you can multiple response for a request. This change make sure we will
retrieve one response from the router at least instead of only waiting
for the first packet.

fix #17

### CODE REVIEW

**Comment by benoitc** [comment]
Maybe the way the timeout is handled can be changed?

**Comment by benoitc** [comment]
cc @macpie

File: src/natupnp_v2.erl [hunk 1]
```diff
@@ -312,24 +328,14 @@ status_info(#nat_upnp{service_url=Url}) ->
...
-            error
-    end.
-
 get_service_url(RootUrl) ->
     case httpc:request(RootUrl) of
         {ok, {{_, 200, _}, _, Body}} ->
             {Xml, _} = xmerl_scan:string(Body, [{space, normalize}]),
             [Device | _] = xmerl_xpath:string("//device", Xml),
             case device_type(Device) of
+                "urn:schemas-upnp-org:device:InternetGatewayDevice:1" ->
```
Comment (benoitc) [inline src/natupnp_v2.erl]: The service was answering with a version 1 instead of 2.

Comment (macpie) [reply src/natupnp_v2.erl]: 👍
